---
title: "Code Book"
author: "Shamaa"
date: "6/21/2021"
output: html_document
---

## Code Book

The *run_analysis.R* script performs data tidying and analysis as described in the course project instructions. The five steps are as follows.  
 
 
 # 1. Download the dataset
 
        + Dataset downloaded and extracted under the folder called UCI HAR Dataset
 
 
 # 2. Assign each data to variables. 
 
        + features <- features.txt : 561 rows, 2 columns 
          The features selected for this database comes from the accelerometer and gyroscope 3-axial raw signals            tAcc-XYZ and tGyro-XYZ.
          
        + data.training.x  <- test/X_train.txt : 7352 rows, 561 columns
          contains recorded features of training data

        + data.training.y <- test/y_train.txt : 7352 rows, 1 columns 
          contains training data of activities’code labels
          
        + data.training.subject <- test/subject_train.txt : 7352 rows, 1 column 
          contains train data of 21/30 volunteer subjects being observed
          
        + *data.training*
          data after merging data.training.x, data.training.y and data.training.subject
          
        + data.test.x <- test/X_test.txt : 2947 rows, 561 columns 
          contains recorded features test data
          
        + data.test.y t <- test/y_test.txt : 2947 rows, 1 columns 
          contains test data of activities’code labels
          
        + data.test.subject <- test/subject_test.txt : 2947 rows, 1 column 
          contains test data of 9/30 volunteer test subjects being observed
          
        + *data.test* 
          data after merging data.test.x, data.test.y and data.test.subject


 # 3. Merges the training and the test sets to create one data set
 
      + *merged_data* was created calling *rbind()* function on data.training and data.test
      
 
 # 4. Extracts only the measurements on the mean and standard deviation for each measurement
 
      + *TidyData*  (10299 rows, 88 columns) is created by selecting (dplyr) only columns: subject, features            and the measurements on the mean and standard deviation (std) for each measurement 
      
 
 # 5. Uses descriptive activity names to name the activities in the data set
 
      + activity.labels <- activity_labels.txt : 6 rows, 2 columns 
        List of activities performed when the corresponding measurements were taken and its codes (labels) 
        
      + Entire numbers in code column of the TidyData is replaced with corresponding activity taken from second         column of the activity.labels variable
      

 # 6. Appropriately labels the data set with descriptive variable names
 
      + code column in TidyData renamed into activities
      + All Acc in column’s name replaced by Accelerometer
      + All Gyro in column’s name replaced by Gyroscope
      + All BodyBody in column’s name replaced by Body
      + All Mag in column’s name replaced by Magnitude
      + All start with character f in column’s name replaced by Frequency
      + All start with character t in column’s name replaced by Time 
 
 
 # 7. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject
 
      + *Final_TidyData* (180 rows, 88 columns) is created by sumarizing TidyData by taking the means of each           variable for each activity and each subject, after being grouped by subject and activity.
      
      + Export Final_TidyData into *Finl_TidyData.txt* file.
